### ISSUE TITLE
Add core functionalities

### ISSUE THREAD

**Issue by TRiyaz47** [ishant9805/TaskFlowr#3]
Add these functionalities in flask
i)add task
ii)delete task/complete dask
iii)Edit task
iv)add deadline function

**Comment by TRiyaz47** [comment]
I can add these functionalities because I do know flask and have added these type functionalities in projects

**Comment by ishant9805** [comment]
Hello, can you add task adding option which connects to sql db containing two tables one which has tasks and one with userID tasks table will have three columns one with task(string) 2nd with user_id and third contains priority and userID table contains two column username and user_id the user_id connects tasks with username. Can you do it?

**Comment by TRiyaz47** [comment]
> Hello, can you add task adding option which connects to sql db containing two tables one which has tasks and one with userID tasks table will have three columns one with task(string) 2nd with user_id and third contains priority and userID table contains two column username and user_id the user_id connects tasks with username. Can you do it?



I think db should contain two tables for this
1)users
user_id
user_name
... etc
2)Task
task_id
task_name
task_description
...etc

I will use mysql workbench  for db

**Comment by ishant9805** [comment]
> > Hello, can you add task adding option which connects to sql db containing two tables one which has tasks and one with userID tasks table will have three columns one with task(string) 2nd with user_id and third contains priority and userID table contains two column username and user_id the user_id connects tasks with username. Can you do it?
> 
> I think db should contain two tables for this 1)users user_id user_name ... etc 2)Task task_id task_name task_description ...etc
> 
> I will use mysql workbench for db

you have been assigned

**Comment by ishant9805** [comment]
@TRiyaz47 are you doing that?

**Comment by ishant9805** [comment]
As I saw your github profile. I don't think you have enough experience with github. Therefore, I am attaching my [LinkedIn](https://www.linkedin.com/in/) here. Ping me there if you need help.

**Comment by TRiyaz47** [comment]
> As I saw your github profile. I don't think you have enough experience with github. Therefore, I am attaching my [LinkedIn](https://www.linkedin.com/in/ishantkumar9805) here. Ping me there if you need help.

Ok thanks

**Comment by TRiyaz47** [comment]
> @TRiyaz47 are you doing that?

Yes

**Comment by TRiyaz47** [comment]
> @TRiyaz47 are you doing that?

Checkout my hms repository, i will do this in same manner, like structure and separate files for db and main

**Comment by ishant9805** [comment]
@TRiyaz47 yeah, I saw that. It will be cool. Just add comments whatever you do and also fetch the repo for new updates.

**Comment by ishant9805** [comment]
@TRiyaz47 just add the functionality. Others will do UI/UX related things and other tasks

**Comment by TRiyaz47** [comment]
> @TRiyaz47 just add the functionality. Others will do UI/UX related things and other tasks

To show something i will add basic UI then others can modify it as per their need

**Comment by TRiyaz47** [comment]
> > @TRiyaz47 just add the functionality. Others will do UI/UX related things and other tasks
> 
> To show something i will add  basic UI then others can modify it as per their need

**Comment by ishant9805** [comment]
Yup, that's what I meant!

**Comment by TRiyaz47** [comment]
> Yup, that's what I meant!

Lets discuss somewhere else like discord

**Comment by ishant9805** [comment]
Will talk to you tomorrow 🙂. Will give you my discord ID or you can send it to me.

**Comment by TRiyaz47** [comment]
> Will talk to you tomorrow 🙂. Will give you my discord ID or you can send it to me. 

My discord username: riyazt#8648

**Comment by TRiyaz47** [comment]
> > Will talk to you tomorrow 🙂. Will give you my discord ID or you can send it to me. 
> 
> My discord username: riyazt#8648

**Comment by TRiyaz47** [comment]
I am now working on this,
I will now implement it using flask in which a user can add, edit ,delete tasks from frontend

**Comment by ishant9805** [comment]
There is no need. Other people are already working on it. Your Pull Request won't be accepted. So, it's totally a waste of time.

**Comment by ishant9805** [comment]
> I am now working on this, I will now implement it using flask in which a user can add, edit ,delete tasks from frontend

why you didn't use SQLAlchemy for SQL operations. If you don't know about it, search and learn.

**Comment by TRiyaz47** [comment]
I do know about Sql alchemy but i think sql workbench is more simple and easy to use

**Comment by TRiyaz47** [comment]
> There is no need. Other people are already working on it. Your Pull Request won't be accepted. So, it's totally a waste of time.
I have already implemented it by now, check my pull request. if you want i can work on sql alchemy

**Comment by ishant9805** [comment]
Sir @TRiyaz47 , you have done your part. Since, you are doing this for hacktober. I will suggest you to contribute to different different projects, not just one. It will make you profile awesome. Thanks again.
