### ISSUE TITLE
Implement database to add,edit,delete tasks

### ISSUE THREAD

**Issue by TRiyaz47** [ishant9805/TaskFlowr#7]
Implement it in MySql workbench and connect it with Python.

**Comment by TRiyaz47** [comment]
I am working on it

**Comment by ishant9805** [comment]
You just need to add the task adding feature and only representative UI nothing more. And adding a db. That's it. Other features will be added by others. As hacktober is going on, the project will be contributed by a lot of others.

**Comment by TRiyaz47** [comment]
I have implemented db and created pull request 
I will do the flask part next if you want

**Comment by ishant9805** [comment]
I reviewed the code. You did a great job. You didn't write the code following the standard rules of coding. You need to learn that. Now you are free to contribute to other projects. Your PR is being accepted.
